### ISSUE TITLE
dúvida

### ISSUE THREAD

**Issue by emalherbi-zz** [vitorvigano/generator-angularseed#2]
Grande Vitor.

Então. resolvi dá uma olhadinha nesse seu projeto ai. Seguindo seu tutorial de como utilizar não vi nada falando do bower porem existem dependências que o utilizam. Pode documentar melhor?

Se eu estiver viajando, desconsidere.

Abrass.

**Comment by vitorvigano** [comment]
E aí man.

Apesar deste gerador usar o Yeoman, não estou utilizando o bower para gerenciar as dependências. Basicamente, criei este gerador para gerar uma versão customizada e mais simples de uma aplicação Angular. Porém, se você pretende criar uma nova, sugiro que use o gerador do angular dos mesmos criadores do Yeoman. Se precisar de um help, estarei feliz em ajudar!

[saiba mais](http://yeoman.io/learning/).

**Comment by emalherbi-zz** [comment]
Ok man. Vou dá mais uma olhada no seu gerador, mas se precisar de ajuda te chamo sim. 
Abrass.

**Comment by vitorvigano** [comment]
Se você quiser contribuir com o projeto também, e aprimorar este gerador, vai ser muito interessante.

Abraço!
