### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arthurnobrega** [vitorvigano/generator-angularseed#4]
In my environment it's not finding the generator after the installation.
### npm install -g generator-angularseed

Output:

```
generator-angularseed@0.1.6 /home/arthur/.node/lib/node_modules/generator-angularseed
└── yeoman-generator@0.13.4 (dargs@0.1.0, debug@0.7.4, diff@1.0.8, rimraf@2.2.8, text-table@0.1.1, mime@1.2.11, async@0.2.10, mkdirp@0.3.5, isbinaryfile@0.1.9, shelljs@0.1.4, underscore.string@2.3.3, iconv-lite@0.2.11, findup-sync@0.1.3, lodash@1.3.1, chalk@0.2.1, glob@3.2.11, tar@0.1.20, request@2.25.0, cheerio@0.12.4, inquirer@0.3.5)
```
### yo angularseed

Output:

```
Error angularseed 

You don't seem to have a generator with the name angularseed installed.
```
## My environment:

**Ubuntu 14.10**
**npm 1.4.28**
**Yeoman 1.3.3**

**Comment by leandroh** [comment]
Hi @arthurnobrega,

What is your Node.js version?

**Comment by arthurnobrega** [comment]
Hey Leandro!

I found the problem, it was  a problem in my installation of Node.js. I followed a step-by-step to remove the necessity to use SUDO in the installation of packages with npm and it caused the problem to don't find the packages that I installed after that.

Thanks! I will close the issue.

**Comment by leandroh** [comment]
It's nice to hear that you've identified the problem correctly.
